---
title: "tweets"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library(tidyverse)
```

```{r,echo=FALSE,warning=FALSE}
raw.data = read.csv("tweets1.csv",row.names = NULL, encoding = "UTF-8")

```

```{r}
unclean_tweets <- raw.data$text
head(unclean_tweets)
```

```{r}
tweet = gsub("&amp", "", unclean_tweets)
tweet = gsub("(RT|via)((?:\\b\\W*@\\w+)+)", "", tweet)
tweet = gsub("@\\w+", "", tweet)
tweet = gsub("[[:punct:]]", "", tweet)
tweet = gsub("[[:digit:]]", "", tweet)
tweet = gsub("http\\w+", "", tweet)
tweet = gsub("[ \t]{2,}", "", tweet)
tweet = gsub("^\\s+|\\s+$", "", tweet) 
head(tweet)
```


```{r}
library(tidyverse)    

clean <- function(x) {
            x %>%
                    str_remove_all(" ?(f|ht)(tp)(s?)(://)(.*)[.|/](.*)") %>%
                    str_replace_all("&amp;", "and") %>%
                    str_remove_all("[[:punct:]]") %>%
                    str_remove_all("^RT:? ") %>%
                    str_remove_all("@[[:alnum:]]+") %>%
                    str_remove_all("#[[:alnum:]]+") %>%
                    str_replace_all("\\\n", " ") %>%
                    str_to_lower() %>%
                    str_trim("both")
    }
tweets <- tweet %>% clean
head(tweets)
```
